### ISSUE TITLE
Missing step/conf 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-openai#10]
# Module: 00
#### Step: 00

Description of issue
When uploading data to Search, we need to provide search type know
![image](https://github.com/MicrosoftLearning/mslearn-openai/assets/64772417/2778b204-ccb1-4ad3-8e86-5ffe9e765f31)

Repro steps:

1.
1.
1.

**Comment by ivorb** [comment]
fixed with PR #12
