### ISSUE TITLE
Azure OpenAI Exercises- Themes

### ISSUE THREAD

**Issue by hkamel** [MicrosoftLearning/mslearn-openai#13]
# Module: 00
#### Step: 00

Description of issue
For all the exercises located here [Azure OpenAI Exercises](https://microsoftlearning.github.io/mslearn-openai/), there is no option to set the content theme similar to the standard MS Lean approach.

Repro steps:

1. Navigate to https://microsoftlearning.github.io/mslearn-openai/ 
1. The Theme for all content is Light
1.

**Comment by ivorb** [comment]
Exercises here are hosted on GitHub pages, not Microsoft Learn, so the themes won't be able to be used for the exercises.
