### ISSUE TITLE
Lab 05 always fails

### ISSUE THREAD

**Issue by theDiverDK** [MicrosoftLearning/mslearn-openai#19]
## Lab/Demo: 05

When running the code for Lab05 Image generation with DALL-E.

I always get an 'The given header was not found' when executing this line:

 var callback_url = init_response.Headers.GetValues("operation-location").FirstOrDefault();
 
 the init_response gives me a 404 error
 
 the AzureOAIEndpoint is the same as in other labs that are working,

**Comment by ivorb** [comment]
I'll look into this - likely moving to SDK for these apps anyway, which should solve the issue

**Comment by theDiverDK** [comment]
Thanks for the update, if you want me to test the solution, just say so :)

**Comment by Jason-Microsoft-MTT** [comment]
When making a call to the API from the provided code in the lab, my response is printing "operation-location", not the URL for the image location. I PROMISE I didnt change any of the code.

<img width="582" alt="image" src="https://github.com/MicrosoftLearning/mslearn-openai/assets/120508481/df732507-fc48-413d-b8d5-e34506fb047d">

**Comment by ivorb** [comment]
SDK for python still doesn't seem to work for DALLE3, so will likely hold off on the SDK update until then. I'll go fix this lab using REST so at least it should work for y'all this week

**Comment by Jason-Microsoft-MTT** [comment]
I actually self-fixed this. I originally grabbed the endpoint from the DALL-E page of AOAI and not the generic endpoint from the resource. That is what was causing the output issue. Once I took a look at the code and saw it was stringifying the api call, thats when I knew I had to use the generic endpoint. 

url = "{}openai/images/generations:submit?api-version={}".format(api_base, api_version)

**Comment by ivorb** [comment]
@Jason-Microsoft-MTT does the lab work for you as written then, once you changed it to the generic endpoint? Do you hit a 404 error like was originally reported?

**Comment by Jason-Microsoft-MTT** [comment]
No, no errors, works fine for me.
________________________________

**Comment by ivorb** [comment]
Verified this works, although does sometimes take a couple minutes for the newly deployed resource to be available - when that happens, you'll see the error this issue originally reported. Added a note to the instructions about that, but the code works as is.
