### ISSUE TITLE
Copy and Paste in Task Description

### ISSUE THREAD

**Issue by eflamm** [MicrosoftLearning/mslearn-openai#24]
# Module: https://microsoftlearning.github.io/mslearn-openai/Instructions/Exercises/05-generate-images.html

Description of issue
Configure your application - refers to text file to be summarized - this is NOT related to image generation.
"Applications for both C# and Python have been provided, as well as a sample text file you’ll use to test the summarization. Both apps feature the same functionality. "
Repro steps:

1.
1.
1.

**Comment by ivorb** [comment]
fixed with c252ed7
