### ISSUE TITLE
Error on lab file 05

### ISSUE THREAD

**Issue by nikkiconley** [MicrosoftLearning/mslearn-openai#26]
# Module: 00
#### Step: generate-image.py

Description of issue
Upon executing the code, line 26 does not complete successfully.  
submission = requests.post(url, headers=headers, json=body)
Printing the error message shows the following error
POST request status code: 404
POST request response: {'error': {'code': 'notFound', 'message': 'Task not found.'}}
As a result, the next command errors and throws an exception:
operation_location = submission.headers['Operation-Location']

Repro steps:

1.
1.
1.

**Comment by Mihai-Ac** [comment]
Hello @nikkiconley 

I have just ran the lab and found no issues with the Python part, I was able to generate images without errors.
Can you re-create the Azure OpenAi resource and try again? ,making sure you use East US region when creating it.

Regards,
Mihai

**Comment by jazzpujols34** [comment]
Hi @nikkiconley ,

I ran into the same issue as you did, and then I took @Mihai-Ac 's advice to use a "eastus" endpoint of AOAI, the code worked.

Btw, you don't have to deploy dalle models, you can just use it for REST API calls.
