### ISSUE TITLE
Single 8-hour lab VM instead of Six 1-hour labs?

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/mslearn-openai#36]
The AI-050 has 6 labs, which are rather similar from the code boiler-plate perspective.   The lab hoster (Skillable) has these as 6 separate labs, each only allows the VM to run for 60-90 minutes.   It wastes a lot of time for 1-day class.  You have to boot up each lab, then re-download the lab files, re-install any packages for Python, build a new OpenAI environment and then deploy a model...  Like 10-15 minutes for each lab.  

Is there any discussion about making this just one 8-hour VM environment so we only have to build everything once, and can then just work through the code for each lab?

**Comment by ivorb** [comment]
It's a requirement to be modular labs for various delivery methodologies and necessary for recycling of AOAI approved subscriptions, so unfortunately a single lab environment isn't possible.
