### ISSUE TITLE
Lab6-YourData: many learners having issues with Search index

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-openai#38]
# Module: 00
#### Step: 10

Description of issue

After saving the data upload/indexing setup, it takes many minutes to finish (even if index is ready , as we can see in Azure Portal).
Many times it even gives a warning of index not found.

WORKAROUND IN CLASS:
1. Delete data source that is failing
2. Connect data source to the Search service > index **margiestravel-index** > same settings as before for rest.

**Comment by ivorb** [comment]
@unaihuete93 are you saying that when the index is ready, just removing the data source connection then re-adding it as a search resource (instead of re-uploading and going through all of that)? I can add that as a note in the instructions if that's helpful

**Comment by unaihuete93** [comment]
Exactly, that workaround fixed it for many.

**Comment by ivorb** [comment]
added with b258ae5
