### ISSUE TITLE
Lab 1 Max length (tokens) --> Max Response

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-openai#39]
# Module: 00
#### Step: 00

Description of issue

line 79

Looks like the paremeter name has been changed 
![image](https://github.com/MicrosoftLearning/mslearn-openai/assets/64772417/88a2fb00-6c38-426c-881e-b74f5ad605e5)

Repro steps:

1.
1.
1.

**Comment by ivorb** [comment]
Fixed
