### ISSUE TITLE
Lab 1 Assistant Setup --> Setup 

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-openai#40]
# Module: 00
#### Step: 00

Description of issue
Not sure if it affects other labs too, **Assistant Setup** has been renamed to **Setup**. Some learners confused it with Assistant (playground).
![image](https://github.com/MicrosoftLearning/mslearn-openai/assets/64772417/8a4c4846-5e62-48a8-8247-f229a1d599f2)

Repro steps:

1.
1.
1.

**Comment by ivorb** [comment]
Fixed
