### ISSUE TITLE
Lab2 azure_oai_deployment

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-openai#41]
# Module: 00
#### Step: 00

Description of issue
Based on the changes introduced by PR https://github.com/MicrosoftLearning/mslearn-openai/pull/34
We need to change instructions line 146 to 
```
model=azure_oai_deployment
```

Repro steps:

1.
1.
1.

**Comment by VincentK16** [comment]
Faced this issue too. Please fixed this ASAP.
