### ISSUE TITLE
Copy/Paste error in Code-Generation lab

### ISSUE THREAD

**Issue by GraemeMalcolm** [MicrosoftLearning/mslearn-openai#5]
In 04-code-generation.md, it looks like the intro paragraph to the **Generate code in chat playground** section was copied from a previous lab (unless the code creates animals with *really* fun names!)

Here's what's there: 

## Generate code in chat playground

Before using your app, examine how prompt engineering improves the model response in the playground. In this first example, imagine you are trying to write a python app of animals with fun names.

**Comment by ivorb** [comment]
exactly what happened - this is resolved
