### ISSUE TITLE
Update Lab 5 to use DALL-E 3 model so that Sweden Central can be an alternative Azure Region

### ISSUE THREAD

**Issue by MSFT-mengchong** [MicrosoftLearning/mslearn-openai#54]
# Module: 5
#### Step: 00

Description of issue
Currently Lab 5 is using DALL-E 2 which is only available in East US.  Suggest using DALL-E 3 which is now available in both East US & Sweden Central to avoid a single point of failure and for load balancing purposes.

Repro steps:

Both C# & Python environment needs to include a third variable to account for the DALL-E 3 deployment ID.  Also the request string the main code body needs to be changed as well.  Reference this document for more details.  https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#request-a-generated-image-dall-e-3

**Comment by GraemeMalcolm** [comment]
We're working on an update to move the lab to DALL-E 3 (in either available region). However, we need to coordinate this change with updates to the corresponding conceptual content on Learn and in the ILT materials.

**Comment by ivorb** [comment]
This has been updated
