### ISSUE TITLE
Lab 03 (Prompt Engineering): Code and instructions not aligned.

### ISSUE THREAD

**Issue by ulkeba** [MicrosoftLearning/mslearn-openai#61]
# Module: "Apply prompt engineering with Azure OpenAI Service"
### Task: "Run your application"

Description of issue

- Instructions say student is supposed to enter system prompt interactively vs. code reads system prompt from system.txt.
- Example prompts contain multi-line user prompts with line breaks but `Console.ReadLine()` will only get the first line and submit this as user prompt.

**Comment by afelix-95** [comment]
> # Module: "Apply prompt engineering with Azure OpenAI Service"
> ## Lab/Demo: 03
> ### Task: "Run your application"
> Description of issue
> 
> * Instructions say student is supposed to enter system prompt interactively vs. code reads system prompt from system.txt.
> * Example prompts contain multi-line user prompts with line breaks but `Console.ReadLine()` will only get the first line and submit this as user prompt.

Regarding the first issue: The app pauses its execution for the user to change the content of `system.txt` and only continues after any input is given in the terminal. That allows the user to change the **System message** interactively for each example prompt, even if not directly through the terminal like the **User message**. 

Regarding the second issue: In VS Code, when you paste multiple lines in the terminal, it should show a warning dialog asking if the user wants to paste each line separately or paste everything as one line. If that warning dialog doesn't appear, you can enable it with the `terminal.integrated.enableMultiLinePasteWarning` setting.
