### ISSUE TITLE
Is missing the new exercise from learning path 6.

### ISSUE THREAD

**Issue by rramoscabral** [MicrosoftLearning/mslearn-openai#65]
# Module: 6
## Lab/Demo: 1

Description of issue

With the March 2024 update, the learning path 6 exercise was changed to 'Exercise: Implement Retrieval Augmented Generation (RAG) with Azure OpenAI Service', previously it was 'Exercise: Use your own data with Azure OpenAI Service'. The repository doesn't have the instructions for the update exercise.

**Comment by ivorb** [comment]
fixed
