### ISSUE TITLE
Web App deployment failed.

### ISSUE THREAD

**Issue by renatocamara** [MicrosoftLearning/mslearn-openai#69]
# Module: 01
#### Step: 02

Description of issue
Client tried to deploy the web app in all regions but with no success.

![image](https://github.com/MicrosoftLearning/mslearn-openai/assets/833283/4cc41ecd-a760-483c-b697-35ab4f5fb0ca)

**Comment by annav88** [comment]
as the error states, the creation is disallowed by policy, so there is nothing wrong with the instruction. The ticket can be closed here, and instead a followup with lab provider is needed.
