### ISSUE TITLE
The lab instructions improvements 

### ISSUE THREAD

**Issue by azakharovams** [MicrosoftLearning/mslearn-openai#7]
# Module: 3
#### Step: 4-6

Description of issue: The guidelines are not clear; it's not specified in which file the modification should be done, and it's not clear when we're referring to PowerShell or Code Editor. Please review the suggested modifications in the repro steps.

Repro steps:
4. Replace "Navigate to the folder for your preferred language and install the necessary packages" with "Install the necessary packages for your preferred language in Bash in your Cloud Shell."
5. Replace "Navigate to your preferred language folder, select the code file, and add the necessary libraries." with "Navigate to your preferred language folder, and open the file named 'test-openai-model.py' or 'program.cs'. Then, add the necessary libraries by including the following code:"
6. Replace "Open up the application code for your language and add the necessary code for building the request, which specifies the various parameters for your model such as prompt and temperature." by "In the same file as in the previous step, add the missing necessary code for building the request. This code specifies various parameters for your model, such as prompt and temperature."

**Comment by GraemeMalcolm** [comment]
We've made some updates to the instructions, and will shortly be making some more significant updates. Thanks for the feedback.
