### ISSUE TITLE
Missing Code Structure

### ISSUE THREAD

**Issue by gerryaobrien** [MicrosoftLearning/mslearn-openai#71]
# Module: 02
#### Step: 00

Description of issue
There is no namespace or main() method in the CSharp Program.cs file.

Repro steps:

1.
1.
1.

**Comment by ivorb** [comment]
In the new format of C# code, explicit definition of `main()` isn't necessary provided there is only one entry point - which is the case here. Try running the code in .NET 7 on the provided VM and you'll see the code runs fine as written. Here's the docs page on top level statements for more info on that structure

**Comment by gerryaobrien** [comment]
Apologies, I should have tried it on another PC to verify.  The first one I used has some framework issues and would not load the program.  Tried it on another and the code works as written.
