### ISSUE TITLE
Unable to deploy your model to a web app 

### ISSUE THREAD

**Issue by awattar** [MicrosoftLearning/mslearn-openai#72]
When trying to deploy model to a web app as stated at the end of the https://microsoftlearning.github.io/mslearn-openai/Instructions/Exercises/01-get-started-azure-openai.html nothing happened. Deployment was in progress for a quite long time (hours) but did not finished.

What could have gone wrong?

**Comment by ivorb** [comment]
It's possible it was just a transient bug in the studio - I was just now able to deploy a web app, though it did take about 20 minutes. Try again? You can also log a bug with the studio, but as of now the instructions are still accurate
