### ISSUE TITLE
Upgrade Labs 1-4 & 6 from GPT 3.5 to GPT-4

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/mslearn-openai#73]
Can these labs please be upgraded from GPT-3.5 to GPT-4? 

There would probably be no appreciable difference, however, we will be showing attendees how to deploy cutting-edge models. 

My understanding is that these labs are on GPT-3.5 purely for historical reasons.

**Comment by ivorb** [comment]
These labs have been tested and verified with GPT 3.5 - they most likely work with GPT 4, but haven't been tested. You're encouraged to still use 3.5, but we'll look at updating them in the near future
