### ISSUE TITLE
Markdown issue for text blocks (ex. prompts)

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/mslearn-openai#74]
There is a Markdown issue that results in applying programming language formatting (C#, perhaps, as the repo default), to English prompt, resulting in strange formatting. For example, note the color coding in Lab 1:

![image](https://github.com/MicrosoftLearning/mslearn-openai/assets/1765732/5be7169c-e203-42f3-80b3-0dc59623ba1d)

Compare with the correct Markdown for Lab 3. All text is consistently styled:

![image](https://github.com/MicrosoftLearning/mslearn-openai/assets/1765732/d0e8bfb2-33d6-42fe-9215-cb606f87e186)

Please adjust Markdown in the impacted labs accordingly.

**Comment by ivorb** [comment]
fixed, I'll keep an eye out for anything I missed

**Comment by VitalyMCT** [comment]
@ivorb Perfect. Thanks for the quick processing!
