### ISSUE TITLE
Cannot complete RAG lab "Add your data" - Failed to validate the selected authentication type

### ISSUE THREAD

**Issue by scottrhay** [MicrosoftLearning/mslearn-openai#76]
# Module: Implement RAG
#### Step: 9

Description of issue
I cannot continue to the Review and finish page going through the Add data process. On the Data connection page, I leave the authentication type at System assigned managed identity and click Next. 

I get the following validation error when clicking next on this page:
Failed to validate the selected authentication type. Please resolve the following errors and click next.Learn more about how to fix validation errors The Azure AI Search resource has disabled RBAC authenticationThe Azure OpenAI resource has disabled system assigned managed identityThe Azure AI Search resource has disabled system assigned managed identity

Repro steps: Run the lab up to this step without any errors. 

Note I'm using the Use your own data with Azure OpenAI Skillable cloud slice for this. The issue affected me and all the students in class (no one was successful).

All of the resources (OpenAI/Search/Storage) are successfully configured in the same region - I've tried with both Australia East and US West regions and both fail with the same error. 

I've tried running the "Add data" process multiple times over 30 minutes so it doesn't appear to be a timing issue. 
![DataConnection_Auth_Error](https://github.com/MicrosoftLearning/mslearn-openai/assets/9246734/68642396-fee2-441e-8a7e-b7c7c6f483ca)

**Comment by iangithub** [comment]
+1
After I configured the service credentials, I still couldn't successfully complete the data connection.

https://learn.microsoft.com/zh-tw/azure/ai-services/openai/how-to/use-your-data-securely#role-assignments

The error was "Principal does not have access to API/Operation."

Additionally, using the F12 developer tools, it was found that Azure OpenAI Studio encountered a 401 issue when sending the API request (api : openai/wednesday-private/preprocessing....).

**Comment by afelix-95** [comment]
I faced the same issues with the system assigned managed identity in the VM, but we can still use the API key authentication to complete the lab.

**Comment by iangithub** [comment]
Complete the following additional settings to successfully finish this Lab.

1.Azure AI Search requires enabling RBAC authentication (selecting both can retain API usage).
2.Azure AI Search enables system assigned managed identity.
3.Azure OpenAI service enables system assigned managed identity.
4.Role assignment.

- Verify the Access control (IAM) for Azure AI Search and grant Azure OpenAI the following roles: Search Index Data Reader, Search Service Contributor.

- Verify the Access control (IAM) for Azure Blob Storage and grant Azure AI Search the following role: Storage Blob Data Contributor.

- Verify the Access control (IAM) for Azure Blob Storage and grant Azure OpenAI the following role: Storage Blob Data Contributor.

- Verify the Access control (IAM) for Azure OpenAI and grant Azure AI Search the following role: Cognitive Services OpenAI Contributor.
