### ISSUE TITLE
Typo on Run your application, Step 10

### ISSUE THREAD

**Issue by llarkan** [MicrosoftLearning/mslearn-openai#8]
# Module: 03
#### Step: 10

Description of issue
Typo

Observe the prompt input, and generated output. This time you'll likely see the email in a similar format, but with a much less informal tone. You'll likely even see jokes included!

Should read:
Observe the prompt input, and generated output. This time you'll likely see the email in a similar format, but with a much more informal tone. You'll likely even see jokes included!

Repro steps:

**Comment by ivorb** [comment]
fixed with faf2810
