### ISSUE TITLE
Module 1 - Cannot deploy model to web app 

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/mslearn-openai#87]
# Module: 01
#### Step: 02

Description of issue

Repro steps:
1. At the top right of the Chat playground page, in the Deploy to menu, select A new web app.

2. In the Deploy to a web app dialog box, create a new web app with the following settings:

- Name: A unique name
- Subscription: CS-SUB-0459
- Resource group: AI-050
- Locations: The region where you provisioned your Azure OpenAI resource
- Pricing plan: Free (F1) - If this is not available, select Basic (B1)
- Enable chat history in the web app: Unselected

Last task - "Deploy your model to a web app" not working with these instructions. See screenshot. 
![image](https://github.com/user-attachments/assets/0b2c9e42-6286-4341-9cf7-c1e724f666e2)

**Comment by ivorb** [comment]
This is a bug in the studio. Added a note about that in the instructions.
