### ISSUE TITLE
Instructions clarification needed regarding AOAI deployment selection

### ISSUE THREAD

**Issue by sanpietro** [MicrosoftLearning/mslearn-openai#88]
#### Step: 04, second point:

Description of issue
We ask user to create two deployments in AOAI: one for embeddings and one for chat.completions. In prior version of lab, embeddings model creation wasn't necessary as we were not utilizing AI Search vectorization. 

Point 2 asks the user to update appsettings.json or .env files with the "deployment name", but does not specify the name of the deployment used for chat.completion. Clarification needs to be added.

![image](https://github.com/user-attachments/assets/6319bfa7-6a3f-461d-9981-d1038ab6419e)

**Comment by ivorb** [comment]
Fixed with f777c6e
