### ISSUE TITLE
Unable to create deployment with gpt-35-turbo model

### ISSUE THREAD

**Issue by llarkan** [MicrosoftLearning/mslearn-openai#9]
# Module: 03
#### Step: 02

Description of issue
Instructions read "In Azure OpenAI Studio, create a new deployment with the following settings:
Model: gpt-35-turbo"

I was unable to complete the instructions because I received an error message when I tried to create a deployment for the gpt-35-turbo model. Please see screen image 1. 

When I selected the command to request more quota, this message was displayed:
**Azure OpenAI Service: Request for Quota Increase
This form is used to submit requests for increased Azure OpenAI TPM (tokens-per-minute) quota.**

Quota increases for text-davinci-003, gpt-35-turbo, and gpt-4 are temporarily paused due to substantial demand for these models.  However, we are accepting requests and will fill them in the order they are received once our process resumes.  Priority will be given to customers who generate traffic that consumes the existing quota allocation, and your request may be denied if this condition is not met.

Please see screen image 2.
link->[Azure OpenAI Service: Request for Quota Increase (microsoft.com)](https://customervoice.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR4xPXO648sJKt4GoXAed-0pURVJWRU4yRTMxRkszU0NXRFFTTEhaT1g1NyQlQCN0PWcu)

**I was able to complete the steps by using the gpt-35-turbo-16k model instead.**

Repro steps:

Followed instructions as written.
<img width="288" alt="Screen image 1" src="https://github.com/MicrosoftLearning/mslearn-openai/assets/44005540/836ad878-ac01-4196-bc76-86e83f1751b4">
![Screen image 2](https://github.com/MicrosoftLearning/mslearn-openai/assets/44005540/28d47fe6-6edf-455f-8cc1-349802245af1)

**Comment by ivorb** [comment]
we discussed this on Teams, but it's due to you having other deployments taking up quota. Try deleting those deployments or other Azure OpenAI resources to regain quota
