### ISSUE TITLE
All sources not working with final Release of Azure.AI.OpenAI

### ISSUE THREAD

**Issue by tobiulm** [MicrosoftLearning/mslearn-openai#91]
# Module: 06
#### Step: 00

Description of issue
All the samples depending on Azure.AI.OpenAI don't work with final Release of Azure.AI.OpenAI (2.0.0) found here https://www.nuget.org/packages/OpenAI/

Repro steps:

1. Instead of referencing Azure.AI.OpenAI  Beta stuff use v2.0.0
2. Some exercises work like Ex2, Ex3 with rewritten code

 This is really sad if you're working for the AI102 Certification or even try to teach a class for AI102 with the latest bits....

**Comment by ivorb** [comment]
library 2.0.0 has breaking changes, so yes the samples as written don't work with the latest release. We have a reorganization of files coming and I'll get these updated to latest shortly after that reorganization. Added to my backlog
