### ISSUE TITLE
azureOpenAI request not working with the "dataSource" parameters

### ISSUE THREAD

**Issue by fivejjs** [MicrosoftLearning/mslearn-openai#93]
https://github.com/MicrosoftLearning/mslearn-openai/blob/7acabf810d9977d15ad3aad80e02304364919a12/Labfiles/06-use-own-data/Python/ownData.py#L47

Error: no "data_sources" filed

**Comment by ivorb** [comment]
did you complete the lab? if you follow those instructions, they specify how you add your data source. If you continue to have issues, please provide more information.
